controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    arm_joint_01:
      type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_joint_01:
  ros__parameters:
    joints:
      - arm_joint_01
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort